– CreateTable CREATE TABLE Brand ( id INT NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL,

PRIMARY KEY (`id`)
Copy
);

– CreateTable CREATE TABLE Product ( id INT NOT NULL AUTO_INCREMENT, title VARCHAR(255) NOT NULL, price INT NOT NULL, createdAt TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updatedAt TIMESTAMP(3) NOT NULL, brandId INT NOT NULL,

PRIMARY KEY (`id`),
CONSTRAINT `Product_brandId_fkey` FOREIGN KEY (`brandId`) REFERENCES `Brand`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
Copy
);